name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H philipmassouh.com >> ~/.ssh/known_hosts

      - name: Pull latest code
        run: ssh pm@philipmassouh.com "cd /var/www/philipmassouh.com/html/food & git pull --ff""
